import subprocess
import threading
import queue
import time
import os
from config.logger import setup_logger

class PersistentShell:
    def __init__(self):
        self.process = None
        self.output_queue = queue.Queue()
        self.is_alive = False
        self.logger = setup_logger("PersistentShell")

    def create_terminal(self):
        """
        Creates a persistent terminal environment (shell).
        """
        self.logger.info("Creating new terminal session...")
        # Use a shell that supports interactive mode well. 
        # /bin/bash or /bin/zsh is common on macOS/Linux.
        shell = os.environ.get('SHELL', '/bin/bash')
        
        self.process = subprocess.Popen(
            [shell],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, # Merge stderr into stdout for simplicity
            text=True,
            bufsize=0, # Unbuffered
            universal_newlines=True
        )
        self.is_alive = True
        
        # Start a thread to read output continuously
        self.reader_thread = threading.Thread(target=self._read_output, daemon=True)
        self.reader_thread.start()
        self.logger.info(f"Terminal session started (PID: {self.process.pid})")
        return self.process.pid

    def _read_output(self):
        """
        Internal method to read stdout from the process and put it in a queue.
        """
        while self.is_alive and self.process and self.process.stdout:
            try:
                # Read character by character to handle prompts and lack of newlines
                char = self.process.stdout.read(1)
                if not char:
                    break
                self.output_queue.put(char)
            except ValueError: # file closed
                break
            except Exception:
                break

    def execute_command(self, command, timeout=2.0):
        """
        Executes a command in the persistent terminal.
        Returns the output generated by this command.
        
        Note: Determining exactly when a command finishes in a raw stream is tricky.
        We use a unique delimiter/sentinel string to detect completion.
        """
        if not self.is_alive or not self.process:
            self.logger.error("Attempted to execute command but terminal is not running.")
            raise RuntimeError("Terminal is not running. Call create_terminal() first.")

        self.logger.info(f"Executing command: {command}")
        
        # Create a unique sentinel to mark the end of the command output
        sentinel = f"__CMD_DONE_{int(time.time())}__"
        
        # We wrap the command to echo the sentinel at the end
        # \n is crucial to execute
        full_command = f"{command}; echo '{sentinel}'\n"
        
        # Clear previous queue content (optional, but safer to avoid reading old garbage)
        # while not self.output_queue.empty():
        #    self.output_queue.get()
        
        self.process.stdin.write(full_command)
        self.process.stdin.flush()
        
        # Collect output until we see the sentinel
        output_buffer = []
        start_time = time.time()
        
        while True:
            try:
                # Blocking get with timeout to prevent infinite hang
                char = self.output_queue.get(timeout=timeout)
                output_buffer.append(char)
                
                # Check if we have the sentinel at the end of the buffer
                # Optimization: only check if we have enough chars
                current_output = "".join(output_buffer)
                if sentinel in current_output:
                    # Remove the sentinel and the command echo (if any)
                    # The command itself might be echoed depending on shell settings (stty echo)
                    
                    # Strip the sentinel
                    result = current_output.replace(sentinel, "").strip()
                    # Also strip the trailing newline from echo if present
                    self.logger.info(f"Command output: {result}")
                    return result
                    
            except queue.Empty:
                # Timeout occurred - maybe command is taking too long or no output
                # For long running commands, this simple logic might need adjustment (e.g. callback)
                # For now, return what we have
                result = "".join(output_buffer)
                self.logger.warning(f"Command execution timed out or no output received. Partial output: {result}")
                return result

    def close_terminal(self):
        """
        Releases the terminal environment.
        """
        if self.process and self.is_alive:
            self.is_alive = False
            # Send exit command
            try:
                self.process.stdin.write("exit\n")
                self.process.stdin.flush()
            except:
                pass
                
            self.process.terminate()
            self.process.wait()
            self.logger.info("Terminal session closed.")
            self.process = None
            